### ISSUE TITLE
Support for !binary tag

### ISSUE THREAD

**Issue by Stefan311** [EsotericSoftware/yamlbeans#104]
Hi,
I have to read yaml files with tags like this: 
`!binary "SSBMaWtlIGJlYW5zIQ=="`
This tag seems to be YAML standard, a Base64 encoded string.
I have already managed to read this as String by insert `reader.getConfig().setClassTag("binary", String.class);`, and doing a base64 decode later, but the problem is the value on this position is not always Base64 encoded, it's also a simple string.

Can you add internal support for the !binary tag, or hint me how to write a proper proxy class?

**Comment by NathanSweet** [comment]
> the problem is the value on this position is not always Base64 encoded, it's also a simple string.

Whether it's YamlBeans or your code, how should it know that the `!binary` tagged value is base64 (needs decoding) or a string (doesn't need decoding)?

**Comment by Stefan311** [comment]
!binary is always Base64 encoded, unencoded strings are without tag
Unencoded:
`- !ruby/object:RPG::EventCommand {i: 0, c: 101, p: ['I Like beans!']}`
Encoded:
`- !ruby/object:RPG::EventCommand {i: 0, c: 101, p: [!binary "SSBMaWtlIGJlYW5zIQ=="]}`

That's what i have now:
`public class RPGEventCommand
{
	public int i;
	public int c;
	public List<Object> p;
}`
`reader.getConfig().setClassTag("binary", String.class);
reader.getConfig().setClassTag("ruby/object:RPG::EventCommand", RPGEventCommand.class);`

**Comment by NathanSweet** [comment]
Ah, gotcha. You can do this:
```
static public class Test {
	public String s1, s2;

	public String toString () {
		return s1 + ", " + s2;
	}
}

static public class BinaryString {
}

static public class BinarySerializer implements ScalarSerializer<String> {
	public String write (String object) throws YamlException {
		return Base64.getEncoder().encodeToString(object.getBytes());
	}

	public String read (String value) throws YamlException {
		return new String(Base64.getDecoder().decode(value));
	}
}

static public void main (String[] args) throws Exception {
	YamlConfig c = new YamlConfig();
	c.setClassTag("binary", BinaryString.class);
	c.setScalarSerializer(BinaryString.class, new BinarySerializer());
	YamlReader r = new YamlReader("{ s1: !binary SSBMaWtlIGJlYW5zIQ==, s2: I Like beans! }", c);
	System.out.println(r.read(Test.class));
}
```

**Comment by NathanSweet** [comment]
Or a little shorter, use BinarySerializer instead of the BinaryString placeholder:
```
```
static public class Test {
	public String s1, s2;

	public String toString () {
		return s1 + ", " + s2;
	}
}

static public class BinarySerializer implements ScalarSerializer<String> {
	public String write (String object) throws YamlException {
		return Base64.getEncoder().encodeToString(object.getBytes());
	}

	public String read (String value) throws YamlException {
		return new String(Base64.getDecoder().decode(value));
	}
}

static public void main (String[] args) throws Exception {
	YamlConfig c = new YamlConfig();
	c.setClassTag("binary", BinarySerializer.class);
	c.setScalarSerializer(BinarySerializer.class, new BinarySerializer());
	YamlReader r = new YamlReader("{ s1: !binary SSBMaWtlIGJlYW5zIQ==, s2: I Like beans! }", c);
	System.out.println(r.read(Test.class));
}
```

**Comment by Stefan311** [comment]
Works! Many thanks!
