### ISSUE TITLE
Version 1.14(?) Deployment (Being able to set Quote char)

### ISSUE THREAD

**Issue by PhilippPfa** [EsotericSoftware/yamlbeans#110]
The newest commit shows the implemented version of the functionality asked for in #108 

Is there already a planned date for deploying this new version? 
I'm using this library for my bachelor thesis work, and it would be nice to set Quote chars as soon as possible

**Comment by NathanSweet** [comment]
I made a new release:
https://github.com/EsotericSoftware/yamlbeans/releases/tag/1.14

**Comment by PhilippPfa** [comment]
That was fast, thank you very much!
Could you also include the new release in the pom.xml? I'm importing the library with maven.

**Comment by NathanSweet** [comment]
Sure, I bumped the version in the pom.xml.

**Comment by IoanaIvanova** [comment]
Hello NathanSweet, 

I saw that you bump the pom.xml version to 1.14 but there is no new version in the [maven repository](https://mvnrepository.com/artifact/com.esotericsoftware.yamlbeans/yamlbeans). Is it possible to release this version also in the maven repository ?

Best Regards,
Yoana
