### ISSUE TITLE
YamlWriter and System.out

### ISSUE THREAD

**Issue by seetamraju** [EsotericSoftware/yamlbeans#111]
When trying to use Stdout/System.out as follows, nothing is output onto console/stdout.
But, when writing to a file, YAML is perfectly output.
Hoping for some tips as to why?  Perhaps I am doing it wrong?
```
// Java 11 on MacOs
com.esotericsoftware.yamlbeans.YamlWriter writer = (outputFilePath.equals("-"))
      ? new com.esotericsoftware.yamlbeans.YamlWriter( new java.io.OutputStreamWriter(System.out) )
      : new com.esotericsoftware.yamlbeans.YamlWriter( new java.io.FileWriter(outputFilePath) );
```

**Comment by NathanSweet** [comment]
Your example doesn't write to nor close the writer.
```
YamlWriter w = new com.esotericsoftware.yamlbeans.YamlWriter(new java.io.OutputStreamWriter(System.out));
w.write("moo");
w.close();
```

**Comment by seetamraju** [comment]
Agree, that will ensure Output is visible on `STDOUT`.
But a big problem.  `System.out` is now closed and it will quietly ignore all further `System.out.println(..)`
Instead.. is there a `flush()` equivalent in `com.esotericsoftware.yamlbeans.YamlWriter`?  .. ..Without closing the `System.out`?
