### ISSUE TITLE
Version 1.14 in maven repository 

### ISSUE THREAD

**Issue by IoanaIvanova** [EsotericSoftware/yamlbeans#112]
Hello, 

I wish to use the new version 1.14 but it is not available in the [maven repository](https://mvnrepository.com/artifact/com.esotericsoftware.yamlbeans/yamlbeans) so I cannot import it as maven dependency. 
I saw that the 1.14 is release in the github releases but could you release it to the maven repository also?

Thanks & Regards,
Yoana

**Comment by Mr14huashao** [comment]
@NathanSweet 
1.14 version is not released to maven repository.

**Comment by NathanSweet** [comment]
I don't have things setup to publish to Maven central. I forgot who did it previously? @Mr14huashao maybe you could handle publishing to Maven central?

**Comment by Mr14huashao** [comment]
Okay, I tried to release version 1.14.

**Comment by Mr14huashao** [comment]
@NathanSweet 
Need you to comment on this ticket (https://issues.sonatype.org/browse/OSSRH-57420)

**Comment by Mr14huashao** [comment]
@NathanSweet 
Version 1.14 has been released.
PR #126 is not released, forget to pull the latest code.

**Comment by Mr14huashao** [comment]
@NathanSweet 
Version 1.14 has been released, this issue can be closed.
![Screenshot from 2020-05-15 10-09-37](https://user-images.githubusercontent.com/57353473/82004207-e7698580-9694-11ea-83a5-d0d7962f3958.png)
