### ISSUE TITLE
AWS Cloudformation YAML

### ISSUE THREAD

**Issue by seetamraju** [EsotericSoftware/yamlbeans#113]
Amazon AWS takes YAML as input, that allows us to configure an entire network, its security and even spin-up new Linux servers -- all via one single YAML file.
See working-sample shown in the attachment.

Specifically, please note the "Exclamation" Mark in quite a few places - WITHOUT any Quotes.
!Equals
!Ref
!Condition
!Or
.. etc ..

Now.. I am writing code..  to generate such YAML.
Map.put( "key", "!Ref" );
I'm using version 1.14
writer.getConfig().writeConfig.setQuoteChar( Quote.NONE );

I'm Not able to make things work.
The Emitter/Writer produces output with single-quotes for '!Equals' '!Ref' '!Condition' .. when there should be no quotes - at all.

Any tips?
Thanks in advance!

Warning: I had to rename the file to .TXT as GitHub does NOT allow uploading YAML files.
[MyNetwork-cloudformation.txt](https://github.com/EsotericSoftware/yamlbeans/files/3168585/MyNetwork-cloudformation.txt)

**Comment by NathanSweet** [comment]
This is an issue tracker to report problems, not a place to ask questions. Please use the mailing list for that.

YamlBeans is not a general purpose YAML library. It is for serializing Java object graphs to/from YAML. You may still be able to do what you want, but you might consider another lib like SnakeYAML.

The `!name` values you are serializing are not data, they are YAML tags for annotating data. YamlBeans uses tags to annotate data for what Java class to use for deserialization. You can use YamlConfig `setClassTag` to map a tag to a class. Eg, `Equals` would map so your class when reading. When writing the class tag will get written only if the Java class definition is not enough to know what the data type is, but you can force tags to always be written using YamlConfig.WriteConfig `setWriteClassname(ALWAYS)`.
