### ISSUE TITLE
YamlWriter does not add quotes and YamlReader throws YamlException: Error parsing YAML.

### ISSUE THREAD

**Issue by stargazer33** [EsotericSoftware/yamlbeans#115]
It seem this magic string:
```
Aaaa ? Iiii, bbb ccc ddd eee. :( ...
```
when passed to YamlWriter (as part of the object graph) - is written into *.yml **without quotes**

When I try to read this *.yml  -- YamlReader throws YamlException: Error parsing YAML.
Tried with both YamlBeans 1.13 and 1.14

I use the following settings:
 yamlConfig.writeConfig.setEscapeUnicode(false);
 yamlConfig.writeConfig.setAutoAnchor(false);
 yamlConfig.writeConfig.setKeepBeanPropertyOrder(true);

**Comment by NathanSweet** [comment]
```
static public void main (String[] args) throws Exception {
	YamlConfig config = new YamlConfig();
	config.writeConfig.quote = Quote.SINGLE;
	
	StringWriter sw = new StringWriter();
	YamlWriter writer = new YamlWriter(sw, config);
	writer.write("abc:(xyz");
	writer.close();
	System.out.println(sw);
	
	YamlReader reader = new YamlReader(sw.toString(), config);
	System.out.println(reader.read());
}
```
This hangs forever. Looks like a problem in Emitter `chooseScalarStyle`. It isn't clear to me what the right fix is and I won't have time to work on it for a while. You are welcome to investigate a fix!

**Comment by stargazer33** [comment]
What is wrong with idea to add quotes... always!

Is it against the YML spec?
May be just as a workaround, as some flag in YmlWriter?

**Comment by NathanSweet** [comment]
It wouldn't be nice to have a setting to always add quotes. You can modify a copy of the lib to do so, of course.

The YAML spec is a painful read and the format is an ugly pig. I don't use it personally.

**Comment by stargazer33** [comment]
> The YAML spec is a painful read and the format is an ugly pig. I don't use it personally.

8-|

Well, I have a production system based on it. It began so simple and easy...

**Comment by Mr14huashao** [comment]
@stargazer33 
I run the following code without throwing any exception.
```java
	@Test
	public void testIssue115() throws YamlException {

		String str = "Aaaa ? Iiii, bbb ccc ddd eee. :( ...";

		YamlConfig config = new YamlConfig();
		config.writeConfig.setEscapeUnicode(false);
		config.writeConfig.setAutoAnchor(false);
		config.writeConfig.setKeepBeanPropertyOrder(true);
		StringWriter sw = new StringWriter();
		YamlWriter writer = new YamlWriter(sw, config);
		writer.write(str);
		writer.close();
		System.out.println(sw);

		YamlReader reader = new YamlReader(sw.toString(), config);
		System.out.println(reader.read());

	}
```
`YamlWriter` can write "Aaaa? Iiii, bbb ccc ddd eee. :( ..." into `sw`
`reader.read()` will hang, I have fixed it.

Is my usage scenario different from yours? If so, can you provide a test case?

**Comment by NathanSweet** [comment]
Can reopen if still a problem.
