### ISSUE TITLE
The problem with the Russian language in YamlWriter

### ISSUE THREAD

**Issue by Sancher17** [EsotericSoftware/yamlbeans#117]
I can't write a file with the Russian language. 
When I tried to write the file I got something like this:

"\u0414\u0430\u0442\u0430 \u0432\u044b\u0445\u043e\u0434\u0430 \u043d\u0430 \u0440\u044b\u043d\u043e\u043a": "2\
   017 \u0433."
"\u041f\u0440\u043e\u0446\u0435\u0441\u0441\u043e\u0440": Intel Celeron

I tried to use this construction:

 YamlWriter writer = new YamlWriter(
                new OutputStreamWriter(new FileOutputStream("/testFile.yml"), "windows-1251"));
        writer.write(details);
        writer.close();

but also no success !!!

**Comment by Mr14huashao** [comment]
@Sancher17 
Add this setting: 
```java
writer.getConfig().writeConfig.emitterConfig.setEscapeUnicode(false);
```

**Comment by Mr14huashao** [comment]
@NathanSweet 
This is not a issue.
