### ISSUE TITLE
yamlbeans is not connected with travis-ci. After the PR submitted by the open source maintainer, it is automatically built and the test case is executed.

### ISSUE THREAD

**Issue by Mr14huashao** [EsotericSoftware/yamlbeans#131]

**Comment by NathanSweet** [comment]
What needs to be done?

**Comment by Mr14huashao** [comment]
Need to be configured in [travis-ci](https://travis-ci.org/account/repositories), but I don’t have permission for this project.

**Comment by Mr14huashao** [comment]
@NathanSweet 
Do not use travis-ci, use github actions.
This issue can be closed.
