### ISSUE TITLE
Forced quotes around string values

### ISSUE THREAD

**Issue by jjkoehorst** [EsotericSoftware/yamlbeans#155]
When generating yaml files I sometimes encounter identifiers such as 79_16 which according to yaml/cwl is an integer even when it is stored in a string object. Is there a way to force quote around string values of a yaml object? When adding quotes around the value within the object it only generates more quotes around the value.

For example: sample: 79_16  should then become sample: '79_16'

I did find the quote option but this only applies to the keys such as sample and not to the value that is supposed to be a string.

**Comment by Mr14huashao** [comment]
@jjkoehorst 
The Quote setting does not take effect in the earlier version of Yamlbeans. This problem has been resolved in the master branch.

Here's a test case:
```java
    @Test
    public void testIssue155() throws YamlException {
        Map<String, String> map = new HashMap<String, String>();
        map.put("sample", "79_16");
        StringWriter sw = new StringWriter();
        YamlConfig yamlConfig = new YamlConfig();
        yamlConfig.writeConfig.setQuoteChar(YamlConfig.Quote.SINGLE);
        YamlWriter yamlWriter = new YamlWriter(sw, yamlConfig);
        yamlWriter.write(map);
        yamlWriter.close();
        System.out.println(sw.toString());
    }
```
**output**
`'sample': '79_16'`

Is that what you want?

**Comment by jjkoehorst** [comment]
Yes indeed that is exactly what I was missing. Thanks!
