### ISSUE TITLE
Default clip chomping on block scalars does not include trailing newline

### ISSUE THREAD

**Issue by jessepav** [EsotericSoftware/yamlbeans#160]
For a block scalar:

```
key1: |
    Text
key2: |-
    Text
```

We find that `key1.equals("Text")` rather than the spec'd `key1.equals("Text\n")`.

In other words, clip chomping behaves like strip chomping (i.e. `key1.equals(key2)`).

**Comment by jessepav** [comment]
I see in `Tokenizer#scanBlockScalarIndicators()` that `chomping` is a boolean, so indeed anything other than *keep* chomping is treated as strip chomping.

The fix doesn't look *too* hard, so perhaps I'll give it a try.

**Comment by NathanSweet** [comment]
You seem to have a better handle on it than I have! PRs are welcome. :)
