### ISSUE TITLE
Relaese Version 1.16 found but the GAV in pom.xml is 1.16-SNAPSHOT

### ISSUE THREAD

**Issue by issssu** [EsotericSoftware/yamlbeans#166]
https://github.com/EsotericSoftware/yamlbeans/releases
![image](https://github.com/EsotericSoftware/yamlbeans/assets/58026012/91859266-1018-4115-be83-4110eb4d7077)

maybe the GAV was not updated:
![image](https://github.com/EsotericSoftware/yamlbeans/assets/58026012/4bd47f5c-f2ee-4def-a98c-328ade2a09e1)

**Comment by NathanSweet** [comment]
Should be good in 1.17.
