### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by pakoito** [EsotericSoftware/yamlbeans#25]
As it is, the library is not currently compatible with Android due to

Caused by: java.lang.ClassNotFoundException: Didn't find class "java.beans.Introspector" on path: DexPathList[[zip file "/data/app/app.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]

Which is a pity because there are not that many YAML libraries out there, and most certainly not as good as yours.

**Comment by NathanSweet** [comment]
This comes up on Android for a number of libs using Introspector. There are
a few projects out there that contain an Introspector implementation you
can drop in, though you may need to change YamlBeans' imports.

In my other serialization projects, I've generally dropped support for
javabeans. Kryo has a BeanSerializer that also uses Introspector, but very
few if any people actually use it, preferring the speed of FieldSerializer.
JsonBeans doesn't support setters/getters at all and I don't think anyone
misses it.

I'd be fine with dropping Introspector from YamlBeans. I've just made the
changes locally, I wonder if I should commit?

**Comment by pakoito** [comment]
You can always branch for Android :dancer:

**Comment by NathanSweet** [comment]
Ended up replacing Introspector with some simple code. Tests still pass so
it must be good, right?

**Comment by pakoito** [comment]
Welp, that was fast lol

Are you pushing a new release or is there a snapshot repo?

**Comment by pakoito** [comment]
Thank you, by the way!

I'll nag you about polymorphism in collections soon enough :-1:

**Comment by Plastix** [comment]
I ran into this error while running my android project with your library. Any chance to release a patch (1.09) in the maven central repo?

**Comment by NathanSweet** [comment]
It's been a long time since YamlBeans was updated. I didn't originally push
it to Maven. I don't actually use Maven, so if someone in the community can
get a new version on Maven central, that would be great.

**Comment by Plastix** [comment]
The `pom.xml` lists `Tony Chemit` as the Maven packager. I assume the PGP keys on maven are his. I'll shoot him an email about pushing a patch build. You should update the version in POM to `1.09`. Thank for your speedy fix and response!

**Comment by NathanSweet** [comment]
Great, thanks! I've updated the POM and made a 1.09 release on GitHub.
https://github.com/EsotericSoftware/yamlbeans/releases/tag/yamlbeans-1.09

**Comment by Plastix** [comment]
@NathanSweet @FranciscoEstevez Tony Chemit has pushed 1.09 to Maven Central.

**Comment by FranciscoEstevez** [comment]
You're a dear, thank you!
