### ISSUE TITLE
Support custom Enum valueOf() method

### ISSUE THREAD

**Issue by itavero** [EsotericSoftware/yamlbeans#37]
YamlReader uses `Enum.valueOf()` to convert Strings to Enumeration values.
Since you cannot override `Enum.valueOf()` and there is now way to influence its behavior, I suggest adding a `SerializableEnum` interface (or a better name if you know one).
This interface should define a method (perhaps `fromString`) that can be used alternatively to `valueOf()` (can have the same interface, I guess).
That way we can sanitize the input (for example, ignore casing) in a way that makes sense to our specific application.
The same can be done for the other way around (YamlWriter).

By the way, why I need this is because of our coding guidelines versus user experience.
Our coding guidelines indicates that the names within the enumeration should be uppercase, however I  do not want to force my users to scream (write everything in caps) in the YAML file.

Also, if I would implement this and it would be approved via a pull request, how long would it take before it would be available on the Maven repository?

**Comment by itavero** [comment]
Totally forgot that static methods in an interface are only allowed since Java 8.
I'm attempting a different approach now. Will post back the results.

**Comment by itavero** [comment]
This issue can be closed once Pull Request #38 is accepted and a new version is released on Maven.

**Comment by daimonion** [comment]
"Our coding guidelines indicates that the names within the enumeration should be uppercase, however I do not want to force my users to scream (write everything in caps) in the YAML file." I think it's pretty common practice. In our projects we also use uppercase values for enumerations, but in the same time we try not to use to much "caps" in yaml configuration.

**Comment by NathanSweet** [comment]
IMO it's just as bad to scream in your code. :)

**Comment by daimonion** [comment]
Pretty good point there :) However, configuration files (it's our most common use for yaml) are "swarmed" with enum values while code usages of enum values are pretty "surgical" and upper case in code suggest that you are dealing with constant value (of course it depends on convention). For some cases it makes code much clearer (while making configuration file less readable).

**Comment by Szilard-IPSystems** [comment]
We need this too. Please accept the [PR](https://github.com/EsotericSoftware/yamlbeans/pull/38).
