### ISSUE TITLE
Support UUID

### ISSUE THREAD

**Issue by FrEaKmAn** [EsotericSoftware/yamlbeans#39]
Hello

Is there a way to add support for UUID? When I try to read from yaml that has UUID

    - !models.Country
        id: f63768b8-b76f-47e8-9882-f15d891ebef9
        name: Afghanistan
        iso2: AF
        iso3: AFG

I get an error

    Caused by: com.esotericsoftware.yamlbeans.YamlReader$YamlReaderException: Line 2, column 4: Expected data for a java.util.UUID field but found: scalar

**Comment by NathanSweet** [comment]
You need to write a serializer.

**Comment by FrEaKmAn** [comment]
Yes, solved with serializer.

```java
public class UUIDSerializer implements ScalarSerializer<UUID>
{
    @Override
    public String write(UUID uuid) throws YamlException
    {
        return uuid.toString();
    }

    @Override
    public UUID read(String s) throws YamlException
    {
        return UUID.fromString(s);
    }
}
```

Maybe this can be in the core?
