### ISSUE TITLE
get map, can't get class

### ISSUE THREAD

**Issue by kingangelAOA** [EsotericSoftware/yamlbeans#42]
---

name: test1
host: http://127.0.0.1
preConditions:
- name: request1
  url: localhost:3000/test1
  method: post
  contentType: json
  body: {"aa":"bbbbb","ccc":[{"ddd":"cccc"}]}
  headers: {'content-type':'application/json'}
- name: request2
  url:
  method:
  contentType: 
  body:
  headers: {'content-type':'application/json'}
  testCases:
- name: test name
  url: localhost:3000/test2
  method: post
  body: {"aa":"${request1.ccc[0].ddd}"}
  headers: {'content-type':'application/json'}
  cookie: {"bbb":"cccc"}
  assert: {"contain":"somestring","jsonPath":"json.path.para:value"}
- name: test name
  url: /api/path
  method: post
  body: {}
  headers: {}
  assert: {"contain":"somestring","jsonPath":"json.path.para:value"}
  package me.ele.api.it.model;

/**
- Created by xuxiaozhi on 11/4/15.
  */
  public class PreCondition {
  private String name;
  private String url;
  private String method;
  private String body;
  private String headers;
  
  public String getName() {
      return name;
  }
  
  public void setName(String name) {
      this.name = name;
  }
  
  public String getUrl() {
      return url;
  }
  
  public void setUrl(String url) {
      this.url = url;
  }
  
  public String getMethod() {
      return method;
  }
  
  public void setMethod(String method) {
      this.method = method;
  }
  
  public String getBody() {
      return body;
  }
  
  public void setBody(String body) {
      this.body = body;
  }
  
  public String getHeaders() {
      return headers;
  }
  
  public void setHeaders(String headers) {
      this.headers = headers;
  }
  }

package me.ele.api.it.model;

import java.util.List;

/**
- Created by xuxiaozhi on 11/4/15.
  */
  public class TestSuite {
  private String name;
  private String host;
  private List<TestCase> testCases;
  private List<PreCondition> preConditions;
  
  public String getHost() {
      return host;
  }
  
  public void setHost(String host) {
      this.host = host;
  }
  
  public List<TestCase> getTestCases() {
      return testCases;
  }
  
  public void setTestCases(List<TestCase> testCases) {
      this.testCases = testCases;
  }
  
  public String getName() {
      return name;
  }
  
  public void setName(String name) {
      this.name = name;
  }
  
  public List<PreCondition> getPreConditions() {
      return preConditions;
  }
  
  public void setPreConditions(List<PreCondition> preConditions) {
      this.preConditions = preConditions;
  }
  }

puts(CaseUtil.getTestSuites("alpha", "/Users/kingangelTOT/yamltest").get(0).getPreConditions().get(0));

Exception in thread "main" java.lang.ClassCastException: java.util.HashMap cannot be cast to me.ele.api.it.model.PreCondition

**Comment by Mr14huashao** [comment]
This should be a usage error.
@kingangelAOA may be used like this:
```java
	Map<String, String> map = new HashMap<String, String>();
	map.put("name", "test name");
	map.put("url", "localhost:3000/test2");
	map.put("method", "post");
	map.put("body", "{\"aa\":\"${request1.ccc[0].ddd}\"}");
	map.put("headers", "{'content-type':'application/json'}");

	StringWriter sw = new StringWriter();
	YamlWriter writer = new YamlWriter(sw);

	writer.write(map);
	writer.close();
	System.out.println(sw);

	String str = sw.toString();
	YamlReader yamlReader = new YamlReader(str);
	PreCondition object = (PreCondition)yamlReader.read();
	System.out.println(object);
```
When deserializing `str`, it will be converted into a map object and forced into PreCondition, and it will definitely throw exception: `java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to com.xxx.PreCondition`.

Correct use, specify type when deserializing:
```java
	Map<String, String> map = new HashMap<String, String>();
	map.put("name", "test name");
	map.put("url", "localhost:3000/test2");
	map.put("method", "post");
	map.put("body", "{\"aa\":\"${request1.ccc[0].ddd}\"}");
	map.put("headers", "{'content-type':'application/json'}");

	StringWriter sw = new StringWriter();
	YamlWriter writer = new YamlWriter(sw);

	writer.write(map);
	writer.close();
	System.out.println(sw);

	String str = sw.toString();
	YamlReader yamlReader = new YamlReader(str);
	PreCondition object = yamlReader.read(PreCondition.class);
	System.out.println(object);
```
@NathanSweet 
This issue is not a problem and can be closed.
