### ISSUE TITLE
is...() Getter Not Recognized for Booleans

### ISSUE THREAD

**Issue by javacraft** [EsotericSoftware/yamlbeans#44]
YamlBeans appears not to recognize that `is...()` is as valid as  `get...()` as a getter method for boolean fields. Case in point, given a boolean field `tangible` its respective getter and setter methods are `isTangible()` and `setTangible(...)`. Unfortunately YamlBeans throws an exception unless a `getTangible()` method is provided.

**Comment by NathanSweet** [comment]
I won't have time for this for a while. A PR is welcome!

**Comment by Mr14huashao** [comment]
@NathanSweet 
This issue has been resolved.
