### ISSUE TITLE
Outdated maven build

### ISSUE THREAD

**Issue by gabriel-pinto** [EsotericSoftware/yamlbeans#47]
I was noticing the read function printing empty lines in my project, but I see that issue has already been resolved, except the maven build is out of date. Are you guys planning on updating it?

**Comment by NathanSweet** [comment]
@tchemit would you be so kind as to do a Maven build?

**Comment by tchemit** [comment]
Hi @NathanSweet , I will manage this today.

**Comment by tchemit** [comment]
Ok done : http://repo1.maven.org/maven2/com/esotericsoftware/yamlbeans/yamlbeans/1.12/

Enjoy.

**Comment by NathanSweet** [comment]
Great, thank you very much @tchemit!
