### ISSUE TITLE
com.esotericsoftware.yamlbeans.YamlException: Error tokenizing YAML.

### ISSUE THREAD

**Issue by zatsepinvl** [EsotericSoftware/yamlbeans#54]
Error above occurs with this input:
```
aa: aaa
 b: bbb
```
The main reason is the white space before "b". Yaml input looks logic, but where is error in parser. Is it so strict specification of YAML or it's just a bug?

**Comment by NathanSweet** [comment]
Your YAML is invalid. Try this:
http://www.yamllint.com/
