### ISSUE TITLE
Throw exception if there is a duplicate key in the YAML

### ISSUE THREAD

**Issue by sanjusoftware** [EsotericSoftware/yamlbeans#57]
we discussed this issue in detail [here](https://groups.google.com/forum/#!topic/yamlbeans-users/dZKp3LnttOM)

as Nate agreed, its better to add this feature on the library. I am signing up to work on this.

**Comment by sanjusoftware** [comment]
@NathanSweet time to close this issue as well then?

**Comment by NathanSweet** [comment]
BTW, a PR is just an issue that has commits. Don't need both an issue and a PR. Cheers!
