### ISSUE TITLE
Numbers in Maps serialized as Numbers, but deserialized as Strings

### ISSUE THREAD

**Issue by TripleWhy** [EsotericSoftware/yamlbeans#65]
YamlWriter makes a difference between Strings and Numbers (as YAML specifies), but YamlReader just treats everything as a String. Is this expected?

Example:

```Java
Map<String, Object> m = new HashMap<>();
m.put("foo", 42);
m.put("bar", "42");

System.out.println("input:");
for (Entry<String, Object> entry : m.entrySet())
	System.out.println(entry.getKey() + ": " + entry.getValue() + " " + entry.getValue().getClass());
System.out.println();

StringWriter buffer = new StringWriter();
YamlWriter writer = new YamlWriter(buffer);
writer.write(m);
writer.close();
String yaml = buffer.toString();
System.out.println("YAML:");
System.out.println(yaml);

YamlReader reader = new YamlReader(yaml);
Map<String, Object> m2 = (Map<String, Object>)reader.read();

System.out.println("deserialized:");
for (Entry<String, Object> entry : m2.entrySet())
	System.out.println(entry.getKey() + ": " + entry.getValue() + " " + entry.getValue().getClass());
```

Output:
```
input:
bar: 42 class java.lang.String
foo: 42 class java.lang.Integer

YAML:
bar: '42'
foo: 42

deserialized:
bar: 42 class java.lang.String
foo: 42 class java.lang.String
```

**Comment by NathanSweet** [comment]
It's been a long time, but I vaguely remember something about YAML trying to guess if a value was a number just because it looks like a number, which I thought was terrible. FWIW, it only matters if you are reading the values as Objects.

**Comment by MikroAcse** [comment]
Subscribing. Really want YamlReader to <read> numbers properly.

**Comment by NathanSweet** [comment]
FWIW, here is where YamlBeans defaults to String when it doesn't know the type and encounters a scalar:
https://github.com/EsotericSoftware/yamlbeans/blob/master/src/com/esotericsoftware/yamlbeans/YamlReader.java#L203
It would need to look at the string value and if it looks like a number, use Integer or Float as the type instead. The `if (type == String.class)` block just after that shows how to get the value as a string. A PR is welcome!
