### ISSUE TITLE
New version to keep order

### ISSUE THREAD

**Issue by cirrus-up-cloud** [EsotericSoftware/yamlbeans#85]
Hi!
Would you like to release a new version of your software in order to make available that fix that keeps read order? I saw fix was commited on June, but last version is from May.

Thanks!

**Comment by raulvc** [comment]
is there a new release available?

**Comment by Mr14huashao** [comment]
@NathanSweet 
This issue is the same as issue #112 , the new version needs to be released to maven repository.
