### ISSUE TITLE
There is test which never ends

### ISSUE THREAD

**Issue by tchemit** [EsotericSoftware/yamlbeans#90]
Method com.esotericsoftware.yamlbeans.YamlWriterTest#testObjects never ends on my computer nor on travis instance (See [travis build]( https://travis-ci.org/tchemit/yamlbeans/jobs/312564603)).

We should fix this before the next release (See #89).

**Comment by NathanSweet** [comment]
Fixed in d0b1b60d2a2da50d2441883bb34392e7cbea0801, sorry!
