### ISSUE TITLE
License BSD-2-Clause vs MIT

### ISSUE THREAD

**Issue by bw-smarkwell** [EsotericSoftware/yamlbeans#96]
In your README.md you describe the project as BSD 2-Clause, but LICENSE.txt is MIT.
It would be helpful to clarify which license the project is released as.

**Comment by NathanSweet** [comment]
Can you show where BSD is mentioned?

**Comment by bw-smarkwell** [comment]
In https://github.com/EsotericSoftware/yamlbeans/blob/master/README.md there is an image linked that says "License BSD 2-Clause" in orange.

**Comment by NathanSweet** [comment]
Ah, I was searching. I didn't put that in there, I don't think. Anyway, I nuked it. Thanks!
